### ISSUE TITLE
issue when run oc new-app

### ISSUE THREAD

**Issue by Mohamed-Elsodany** [dudash/openshiftexamples-autoscaling#5]
Hello,
i get this issue when i run the command for building the pod, i am using minishift environment

C:\Users\xyz>oc new-app -f https://raw.githubusercontent.com/dudash/openshiftexamples-autoscaling/master/autoscale_instant_template.yaml
warning: Cannot find git. Ensure that it is installed and in your path. Git is required to work with git repositories.
--> Deploying template "autoscaledemo/autoscale-instantapp-template.yaml" for "https://raw.githubusercontent.com/dudash/openshiftexamples-autoscaling/master/autoscale_instant_template.yaml" to project autoscaledemo

     * With parameters:
        * Namespace=autoscaledemo

--> Creating resources ...
    secret "mongodb" created
    persistentvolumeclaim "mongodb" created
    imagestream "webapp" created
    buildconfig "webapp" created
    deploymentconfig "mongodb" created
    deploymentconfig "webapp" created
    route "webapp" created
    service "mongodb" created
    service "webapp" created
    error: unable to recognize extensions/v1beta1, Kind=HorizontalPodAutoscaler: no matches for extensions/, Kind=HorizontalPodAutoscaler
--> Failed

any help please ?

Thanks

**Comment by dudash** [comment]
Hi Mohamed, 
Sorry I somehow missed the notification on this issue.  This should be fixed now.
The template for the hpa using a beta api spec.
